### ISSUE TITLE
Intégration au projet VT2

### ISSUE THREAD

**Issue by indydedeken** [Desiderius77/VT2bis#12]

**Comment by indydedeken** [comment]
Nous travaillons toujours sur cette intégration à VT2. 

Cependant nous rencontrons un problème pour réaliser la connexion avec les login/mdp de VTAgenda. Cela puisque les mots de passes sont cryptés en MD5 ; or le <code>MD5 de Apache</code> n'est pas iso au <code>MD5 de MySQL</code>. 

L'une des solutions étudiées est d'utiliser un module Apache iso MySQL : 
- **mod_auth_mysql**

___

##### Quelques sources 
- http://www.ixany.org/docs/Apache_mod_auth_mysql.html
- https://alimanfoo.wordpress.com/2010/11/17/apache-authentication-and-mysql/
- http://modauthmysql.sourceforge.net/

**Comment by edouardalvescamilo** [comment]
J'ai rencontré quelques soucis relatifs à la mise en place du module **mod_auth_mysql**. Les directives saisies dans le VirtualHost n'étaient pas reconnues malgré mes différentes tentatives. 

Après réinstallation de l'ensemble des composants du serveur web, le module fonctionne correctement.

**Solution finale retenue** : mod_auth_mysql couplé avec la base originale de VT_AGENDA.

Je mets à jour le Wiki en conséquence.

**Comment by Desiderius77** [comment]
Un grand merci à vous tous pour cet effort supplémentaire !

Vous en serez largement récompensé non seulement par la note qui est d'ores et déjà bonne mais surtout par l'utilisation très large qui va être faite de votre projet

**Comment by edouardalvescamilo** [comment]
Wiki mis à jour: https://github.com/Desiderius77/VT2bis/wiki/%5BApache%5D-VirtualHost-&-SSL
